### ISSUE TITLE
After clicking photo, stuck in full screen mode

### ISSUE THREAD

**Issue by mrcampbell06** [ronakg/awesome-flickr-gallery-plugin#95]
I installed the plugin and linked my photostream gallery.
Now when i click on the photo. The screen goes full screen and shows the picture. I am unable to get out of the full screen mode , to view the website/gallery.

http://truelight-estl.com/photos/

**Comment by ronakg** [comment]
Looks like there's some issue rendering the X on top right corner to close the slideshow view. However, clicking the top right corner of the website does close it. Hitting Esc key on the keyboard also works.

Note that AFG doesn't support videos yet, so playing a video won't work.

**Comment by mrcampbell06** [comment]
Its not a video, but it a photo screen shot of a video. :-)

**Comment by mrcampbell06** [comment]
Is this a known issue? or can I do something to fix the X rendering. Right now its not really user friendly?

**Comment by ronakg** [comment]
No this is not a known issue. I see that there are multiple versions of jquery being loaded on your website. Your theme is loading it's own jquery script instead of loading the one that comes built into wordpress for example.

This can cause conflicts and behaviors like you are seeing. It will be very difficult to narrow down the issue here.
